server:
  port: 8085
spring:
  application:
    name: gateway
  ldap:
    urls: ldap://localhost:389
    base: dc=empresa,dc=com
    username: cn=admin,dc=empresa,dc=com
    password: adminpassword123
  cloud:
    gateway:
      routes:
        - id: mi_servicio
          uri: https://httpbin.org # URL de prueba a la que redirigir
          predicates:
            - Path=/get/**
