server:
  port: 8081
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
spring:
  application:
    name: gateway
  ldap:
    urls: ldap://localhost:389
    base: dc=empresa,dc=com
    username: cn=admin,dc=empresa,dc=com
    password: adminpassword123
#  cloud:
#    gateway:
#      routes:
#      - id: products-service
#        uri: http://localhost:8086
#        predicates:
#          - Path=/api/products/**, /api/products
#          - Method=GET,POST,PUT,DELETE