server:
  port: 8085
spring:
  application:
    name: gateway
  ldap:
    urls: ldap://localhost:389
    base: dc=empresa,dc=com
    username: cn=admin,dc=empresa,dc=com
    password: adminpassword123
#  cloud:
#    gateway:
#      routes:
#        - id: products-service
#          uri: http://localhost:8086
#          predicates:
#            - name: Path
#              args:
#                patterns:
#                  - /api/products
#                  - /api/products/**